#!/bin/sh
# Usage: firstboot-unattended
#
set -fu

while getopts 'h' opt; do
    case "${opt}" in
        'h')
            printf 'Usage: %s\n' "${0}"
            exit 0
        ;;
        *)
            printf 'Usage error.\n' 1>&2
            exit 64
        ;;
    esac
done

[ ${OPTIND} -lt 2 ] || shift $(( OPTIND - 1 ))

if [ $# -gt 0 ]; then
    printf 'Usage error.\n' 1>&2
    exit 64
fi

# Remove flag file to prevent repeated firstboot runs [FATAL]
# (and safeguard against unintended invocations)
if ! rm -v -- /firstboot_mode; then
    printf 'Could not remove /firstboot_mode flag file, aborting.' 1>&2
    exit 2
fi

# Disable firstboot init hook [NONFATAL]
(
    if [ -d /run/systemd/system ]; then
        systemctl disable dbuild-firstboot.service

    else
        # XXX
        printf 'FIXME, NOT IMPLEMENTED: sysv disable dbuild-firstboot\n' 1>&2
    fi
) || :

# Remove firstboot initramfs hooks/scripts [NONFATAL]
(
    printf 'Removing firstboot initramfs scripts\n'
    find /etc/initramfs-tools -type f -name 'firstboot*' -delete
) || :


# Update initramfs, (re)install GRUB [FATAL]
(
    printf 'Rebuilding initramfs\n'
    # update initramfs in non-firstboot mode, (re)install grub
    INITRAMFS_FIRSTBOOT="" update-initramfs -u -k all || exit

    printf 'Reinstalling GRUB\n'
    grub-install || exit
    update-grub || exit
) || exit


# remove factory /etc/fstab [NONFATAL]
(
    printf 'Removing factory /etc/fstab\n'
    rm -- /etc/fstab.initial || :
) || :
