#!/bin/sh
# nftables

PREREQ=""

prereqs() {
    echo "$PREREQ"
}

case "${1-}" in
    prereqs)
        prereqs
        exit 0
    ;;
esac

. /scripts/functions
# Begin real processing below this line


nftables_write_kmsg_status() {
    [ -c /dev/kmsg ] || return 0
    printf 'early-nftables: %s\n' "${1:-unknown}" > /dev/kmsg
}


if [ -s /etc/nftables.conf ]; then
    if nft -f /etc/nftables.conf; then
        log_success_msg "Early firewall rules have been loaded."
        nftables_write_kmsg_status success || :

    else
        log_failure_msg "Could not load early firewall rules."
        nftables_write_kmsg_status failed || :
    fi

else
    log_warning_msg "Skipping early firewall rules, rules file is missing or empty."
    nftables_write_kmsg_status skipped || :
fi
