#!/bin/sh
# firstboot-kvm

PREREQ="firstboot"

prereqs() {
    echo "$PREREQ"
}

case "${1-}" in
    prereqs)
        prereqs
        exit 0
    ;;
esac

. /scripts/functions
# Begin real processing below this line


if [ -e /can_firstboot ] && [ "${firstboot:-0}" = '1' ]; then
    mount -o remount,rw "${rootmnt:?}" || :
    # NOTE: keeping rootmnt in read-write mode!

    rm -f -- "${rootmnt:?}/etc/fstab.initial"

    if \
        {
            cp -L -- /run/initramfs/fstab.host "${rootmnt:?}/etc/fstab.firstboot" && \
            ln -f -- "${rootmnt:?}/etc/fstab" "${rootmnt:?}/etc/fstab.initial" && \
            mv -f -- "${rootmnt:?}/etc/fstab.firstboot" "${rootmnt:?}/etc/fstab"
        }
    then
        log_success_msg "Installed new /etc/fstab file"
    else
        log_failure_msg "Could not install new /etc/fstab file"
    fi
fi
