#!/bin/sh

PREREQ=""

prereqs() {
    echo "$PREREQ"
}

case "${1-}" in
    prereqs)
        prereqs
        exit 0
    ;;
esac

. /usr/share/initramfs-tools/hook-functions
# Begin real processing below this line

verbose() {
    #if [ "${verbose-}" = "y" ]; then
    printf 'I: firstboot: %s\n' "${@}"
    #fi
}

if [ -n "${INITRAMFS_FIRSTBOOT-}" ]; then
    verbose 'Enabling firstboot mode support'
    touch -- "${DESTDIR:?}/can_firstboot"

else
    rm -f -- "${DESTDIR:?}/can_firstboot"
fi
